version: '2'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - mc_db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root

  mc1:
    build: ../mc1
    image: mc1:latest
    ports:
      - "8081:8080"
    restart: on-failure
    depends_on:
      - mariadb

  mc2:
    build: ../mc2
    image: mc2:latest
    ports:
      - "8082:8080"
    restart: on-failure
    depends_on:
      - kafka
      - mc1

  mc3:
    build: ../mc3
    image: mc3:latest
    ports:
      - "8083:8080"
    restart: on-failure
    depends_on:
      - kafka

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "5778:5778"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mc_db_data:
